# Generated by Django 5.1.6 on 2025-03-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('trainee_app', '0002_trainee_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='courses',
        ),
        migrations.AddField(
            model_name='trainee',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course_app.course'),
        ),
    ]
