# Generated by Django 5.1.6 on 2025-03-14 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
        ('trainee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='courses',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_app.course'),
        ),
    ]
